Update documentation discrepancies
heritagefund/tech-docs pull request #31
Opened 2020-10-19 09:36 UTC by ptrelease

Corrected documentation where we discovered upon migration that some proposed tables didn't pan out.

2020-10-23 07:13 UTC, stuartmccoll requested changes

2020-10-23 07:13 UTC, stuartmccoll commented on source/documentation/data_dictionary/tables/_declarations.md
>    json: JSON                    A structured version of a declaration
We've got this in as a `jsonb` column.

2020-10-23 07:13 UTC, stuartmccoll commented on source/documentation/data_dictionary/tables/_funding_applications.md
> +Table that contains details specific to a funding application.  The current application table may contain additional rows as originally declaration data was kept on this table.
What do we mean by 'additional rows' here?

2020-10-23 07:13 UTC, stuartmccoll commented on source/documentation/data_dictionary/tables/_organisations_org_types.md
> +Link table between and organisation and organisation types.
```suggestion
Link table between organisations and organisation types.
```

2020-10-23 07:13 UTC, stuartmccoll commented on source/documentation/data_dictionary/tables/_organisations_org_types.md
> +## organisation_org_types
```suggestion
## organisations_org_types
```

2020-10-26 10:08 UTC, ptrelease commented on source/documentation/data_dictionary/tables/_cash_contributions.md
> +application_id: UUID <<FK>>         Currently called project Id.
changed

2020-10-26 10:24 UTC, ptrelease commented on source/documentation/data_dictionary/tables/_declarations.md
> +  updated_at : Timestamp
changed

2020-10-26 10:24 UTC, ptrelease commented on source/documentation/data_dictionary/tables/_declarations.md
>    json: JSON                    A structured version of a declaration
changed

2020-10-26 10:25 UTC, ptrelease commented on source/documentation/data_dictionary/tables/_funding_applications.md
> +Table that contains details specific to a funding application.  The current application table may contain additional rows as originally declaration data was kept on this table.
Changed to fields

2020-10-26 21:29 UTC, stuartmccoll approved these changes

2020-10-26 21:30 UTC, merged